### ISSUE TITLE
Battery Saves sometimes not working

### ISSUE THREAD

**Issue by rtretiakov** [libretro/bsnes#2]
Some users have reported this issue. I am unable to reproduce the issue.
I have tried saving in, and outside of the content directory.
If anyone can reproduce this, please post details here.

**Comment by Zeigfried-McBacon** [comment]
I'm having this issue with this core myself and here's what I've noticed so far.
*No permanent file for the save is being written, but it will hold a a save file until the retroarch or even just the core is closed.
*Doesn't seem to read saves (.srm) files from the chosen directory either.
for reference, I'm running windows 10, retroarch has administrative rights, and the SNES9X's core doesn't give me these save issues. I noticed the issue with v109.1 earlier today and the issue still seems to happen on v109.3 (the latest one I can download as of this posting). 
Not sure how much this helps, but if there's anything more I can do, just give me the instructions and Ill comply as best as I can. Thanks!

**Comment by rtretiakov** [comment]
Thanks for the information @Zeigfried-McBacon. Do you have the same problems with the libretro higan core? When I created this port I lifted a lot of code from there. I may have missed something at that time.

**Comment by Zeigfried-McBacon** [comment]
Higan-Accuracy? Never used that core before, but I'll test it out and see if it pops up there as well.

Edit:Update; the higan core I was able to get seems to do saves just fine.

**Comment by Tathagata-0** [comment]
I'm having this issue as well, matching exactly what happens for Zeigfried. If it helps, I have a log: https://pastebin.com/HaprT1FM

**Comment by 1985a** [comment]
Hi, excuse me if I'm wrong using this thread but it is concerned about the battery's save file. I was using the previous version, so last night because I'm at work now, I compile this core and my save file for a hack of Super Mario went to zero. I don't know what it happened here.

Apparently, this core's corrupted the savefile. Before that, I could play in both, the core version and standalone version. Now neither bsnes nor core doesn't see my savefile.

https://www.romhacking.net/hacks/1310/

This is the hack that I was playing. 

I'm going to post the savefile tomorrow

**Comment by rtretiakov** [comment]
I reproduced the problem and fixed it. Please let me know if it works for everyone after you update your core to the latest build once the buildbot finishes.

**Comment by 1985a** [comment]
In my case, it doesn't work yet.

The core, just refuse to load my save file.

BTW, I'm using Linux.

They are the same savefile and i can share between them. Now i dont know why it is not working.
[pictures](https://imgur.com/a/pH4BgJd)

**Comment by Tathagata-0** [comment]
Same for me, still isn't working on v110.

**Comment by rtretiakov** [comment]
@TathagataDM would you be able to post another log using the latest build? It might help me figure out the problem. I am sure it has to do with paths at some level.

@1985a would you also be able to paste a verbose log?

**Comment by Zeigfried-McBacon** [comment]
110 is working no differently than the 109 cores so Ill leave my log and hope that helps.

**Comment by Tathagata-0** [comment]
Yep, here's a new log from v110: https://pastebin.com/DnJpWzYi

**Comment by 1985a** [comment]
Hi there, I was at the University today. 

Now I was able to figure out the problem.

I test a new save file and it just works well.

Then, I think, jummm something here is wrong, just made a "ls -lrt" to see which folder was modified

Apparently, the problem is that old cores versions named as bsnes HD, now it is Bsnes.

I put it the save file in, and just loaded it.

[image](https://imgur.com/QVFF7w2)

[line210](https://pastebin.com/nM4ivt6K)

Now, everything is OK!

pd: my English is still improving, sorry the mistakes.

**Comment by Zeigfried-McBacon** [comment]
I dont know what was changed since my last post but it seems to be working for me now.

**Comment by Tathagata-0** [comment]
It's working on my end now as well with the latest update. Thanks @rtretiakov!

**Comment by rtretiakov** [comment]
Great to hear, everyone. I guess it took some time for the new build to go out. Thanks for helping to get this issue resolved.
